EXTENSION = exe_worker
DATA = exe_worker--1.0.sql
MODULES = exe_worker
#REGRESS = pg_make_title
ifdef USE_PGXS
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
else
subdir = contrib/exe_worker
top_builddir = ../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/contrib/contrib-global.mk
endif
